version: "3.4"

services:
  app:
    image: be-ticket-vintrip/express:v1
    container_name: ticket-vintrip-be
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file: .env
    volumes: 
      - ./coverage:/app/coverage
networks:
  default:
    name: ols
    external: true