[
  {
    id: 1,
    name: "Nhân sự ",
    slug: "profile-service ",
    description: null,
    domain: "https://employee.tuoitre.vn ",
    status: 1,
    created_at: "2022-02-21T07:17:22.000000Z ",
    updated_at: "2022-02-21T07:17:22.000000Z ",
    groups: [
      {
        id: 1,
        service_management_id: 1,
        name: "Hồ sơ ",
        slug: "profile ",
        status: 1,
        service_name: "Nhân sự ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 1,
            table_management_id: 1,
            name: "Tạo hồ sơ ",
            uri: "api/profiles ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01 ",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 2,
            table_management_id: 1,
            name: "Sửa hồ sơ ",
            uri: "api/profiles/{profile} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01 ",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 3,
            table_management_id: 1,
            name: "Xoá hồ sơ ",
            uri: "api/profiles/{profile} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01 ",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 4,
            table_management_id: 1,
            name: "Xem chi tiết hồ sơ bằng user id ",
            uri: "api/fe/profiles/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 5,
            table_management_id: 1,
            name: "Xem chi tiết hồ sơ bằng profile id",
            uri: "api/fe/profiles/{profile_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 6,
            table_management_id: 1,
            name: "Xem danh sách hồ sơ",
            uri: "api/profiles",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 7,
            table_management_id: 1,
            name: "Tạo phòng ban",
            uri: "api/departments",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 2,
        service_management_id: 1,
        name: "Phòng ban",
        slug: "department",
        status: 1,
        service_name: "Nhân sự",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 8,
            table_management_id: 2,
            name: "Tạo phòng ban",
            uri: "api/departments",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 9,
            table_management_id: 2,
            name: "Sửa phòng ban",
            uri: "api/departments/{department}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 10,
            table_management_id: 2,
            name: "Xoá phòng ban",
            uri: "api/departments/{department}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 11,
            table_management_id: 2,
            name: "Xem chi tiết phòng ban",
            uri: "api/departments/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 12,
            table_management_id: 2,
            name: "Xem danh sách phòng ban",
            uri: "api/departments",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 3,
        service_management_id: 1,
        name: "Lịch sử cá nhân",
        slug: "personal-history",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 26,
            table_management_id: 3,
            name: "Tạo lịch sử cá nhân",
            uri: "api/personal-histories",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 27,
            table_management_id: 3,
            name: "Sửa lịch sử cá nhân",
            uri: "api/personal-histories/{personal_history}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 28,
            table_management_id: 3,
            name: "Xoá lịch sử cá nhân",
            uri: "api/personal-histories/{personal_history}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 29,
            table_management_id: 3,
            name: "Xem chi tiết lịch sử cá nhân",
            uri: "api/personal-histories/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 30,
            table_management_id: 3,
            name: "Xem danh sách lịch sử cá nhân",
            uri: "api/personal-histories",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 4,
        service_management_id: 1,
        name: "Đối tượng lao động",
        slug: "work-object",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 31,
            table_management_id: 4,
            name: "Tạo đối tượng lao động",
            uri: "api/work-objects",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 32,
            table_management_id: 4,
            name: "Sửa đối tượng lao động",
            uri: "api/work-objects/{work_object}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 33,
            table_management_id: 4,
            name: "Xoá đối tượng lao động",
            uri: "api/work-objects/{work_object}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 34,
            table_management_id: 4,
            name: "Xem chi tiết đối tượng lao động",
            uri: "api/work-objects/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 35,
            table_management_id: 4,
            name: "Xem danh sách đối tượng lao động",
            uri: "api/work-objects",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 5,
        service_management_id: 1,
        name: "Thẻ nhà báo",
        slug: "journalist-card",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 13,
            table_management_id: 5,
            name: "Tạo thẻ nhà báo",
            uri: "api/journalist-cards",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 14,
            table_management_id: 5,
            name: "Sửa thẻ nhà báo",
            uri: "api/journalist-cards/{journalist_card}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 15,
            table_management_id: 5,
            name: "Xoá thẻ nhà báo",
            uri: "api/journalist-cards/{journalist_card}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 16,
            table_management_id: 5,
            name: "Xem chi tiết thẻ nhà báo",
            uri: "api/journalist-cards/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 17,
            table_management_id: 5,
            name: "Xem danh sách thẻ nhà báo",
            uri: "api/journalist-cards",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 6,
        service_management_id: 1,
        name: "Trình độ",
        slug: "user-degree",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 36,
            table_management_id: 6,
            name: "Tạo trình độ của đối tượng",
            uri: "api/user-degrees",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 37,
            table_management_id: 6,
            name: "Sửa trình độ của đối tượng",
            uri: "api/user-degrees/{user_degree}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 38,
            table_management_id: 6,
            name: "Xoá trình độ của đối tượng",
            uri: "api/user-degrees/{user_degree}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 39,
            table_management_id: 6,
            name: "Xem chi tiết trình độ của đối tượng",
            uri: "api/user-degrees/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 40,
            table_management_id: 6,
            name: "Xem danh sách trình độ của đối tượng",
            uri: "api/user-degrees",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 7,
        service_management_id: 1,
        name: "Bộ phận làm việc",
        slug: "part",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 18,
            table_management_id: 7,
            name: "Tạo bộ phận làm việc",
            uri: "api/parts",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 19,
            table_management_id: 7,
            name: "Sửa bộ phận làm việc",
            uri: "api/parts/{part}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 20,
            table_management_id: 7,
            name: "Xoá bộ phận làm việc",
            uri: "api/parts/{part}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 21,
            table_management_id: 7,
            name: "Xem danh sách bộ phận làm việc",
            uri: "api/parts",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 8,
        service_management_id: 1,
        name: "Vị trí làm việc",
        slug: "position",
        status: 1,
        service_name: "Nhân sự",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 22,
            table_management_id: 8,
            name: "Tạo vị trí làm việc",
            uri: "api/positions",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 23,
            table_management_id: 8,
            name: "Sửa vị trí làm việc",
            uri: "api/positions/{position}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 24,
            table_management_id: 8,
            name: "Xoá vị trí làm việc",
            uri: "api/positions/{position}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
          {
            id: 25,
            table_management_id: 8,
            name: "Xem danh sách vị trí làm việc",
            uri: "api/positions",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:01",
            updated_at: "2022-03-10 09:26:01",
          },
        ],
      },
      {
        id: 14,
        service_management_id: 1,
        name: "Đi nước ngoài",
        slug: "go-abroad",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 46,
            table_management_id: 14,
            name: "Tạo quan hệ gia đình",
            uri: "api/family-relationship",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 47,
            table_management_id: 14,
            name: "Sửa quan hệ gia đình",
            uri: "api/family-relationship/{family_relationship}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 48,
            table_management_id: 14,
            name: "Xoá quan hệ gia đình",
            uri: "api/family-relationship/{family_relationship}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 49,
            table_management_id: 14,
            name: "Xem chi tiết quan hệ gia đình",
            uri: "api/family-relationship/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 50,
            table_management_id: 14,
            name: "Xem danh sách quan hệ gia đình",
            uri: "api/family-relationship",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 15,
        service_management_id: 1,
        name: "Quan hệ gia đình",
        slug: "family-relationship",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 51,
            table_management_id: 15,
            name: "Tạo khen thưởng và kỷ luật",
            uri: "api/reward-discipline",
            method: "post",
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 52,
            table_management_id: 15,
            name: "Sửa khen thưởng và kỷ luật",
            uri: "api/reward-discipline/{reward_discipline}",
            method: "put",
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 53,
            table_management_id: 15,
            name: "Xoá khen thưởng và kỷ luật",
            uri: "api/reward-discipline/{reward_discipline}",
            method: "delete",
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 54,
            table_management_id: 15,
            name: "Xem chi tiết khen thưởng và kỷ luật",
            uri: "api/reward-discipline/users/{user_id}",
            method: "get",
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 55,
            table_management_id: 15,
            name: "Xem danh sách khen thưởng và kỷ luật",
            uri: "api/reward-discipline",
            method: "get",
            action: "list",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 16,
        service_management_id: 1,
        name: "Khen thưởng và kỷ luật",
        slug: "reward-discipline",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 56,
            table_management_id: 16,
            name: "Tạo quy trình làm việc",
            uri: "api/workflow/store",
            method: null,
            action: "create",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 57,
            table_management_id: 16,
            name: "Cập nhật quy trình làm việc",
            uri: "api/workflow/store",
            method: null,
            action: "update",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 58,
            table_management_id: 16,
            name: "Xóa quy trình làm việc",
            uri: "api/workflow/store",
            method: null,
            action: "delete",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 59,
            table_management_id: 16,
            name: "Xem quy trình làm việc",
            uri: null,
            method: null,
            action: "view",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 21,
        service_management_id: 1,
        name: "Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ",
        slug: "training-fostering",
        status: 1,
        service_name: "Nhân sự",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z",
        updated_at: "2022-02-21T07:17:22.000000Z",
        permissions: [
          {
            id: 72,
            table_management_id: 21,
            name: "Tạo Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
            uri: "api/organization ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 73,
            table_management_id: 21,
            name: "Sửa Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
            uri: "api/organization/{organization} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 74,
            table_management_id: 21,
            name: "Xoá Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
            uri: "api/organization/{organization} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 75,
            table_management_id: 21,
            name: "Xem chi tiết Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
            uri: "api/organization/users/{user_id} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 76,
            table_management_id: 21,
            name: "Xem danh sách Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
            uri: "api/organization ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 22,
        service_management_id: 1,
        name: "Tham gia các tổ chức chính trị, xã hội, các nghề nghiệp ",
        slug: "organization ",
        status: 1,
        service_name: "Nhân sự ",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 77,
            table_management_id: 22,
            name: "Tạo Gia nhập Đảng Cộng Sản Việt Nam ",
            uri: "api/party ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 78,
            table_management_id: 22,
            name: "Sửa Gia nhập Đảng Cộng Sản Việt Nam ",
            uri: "api/party/{party} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 79,
            table_management_id: 22,
            name: "Xoá Gia nhập Đảng Cộng Sản Việt Nam ",
            uri: "api/party/{party} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 80,
            table_management_id: 22,
            name: "Xem chi tiết Gia nhập Đảng Cộng Sản Việt Nam ",
            uri: "api/party/users/{user_id} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 81,
            table_management_id: 22,
            name: "Xem danh sách Gia nhập Đảng Cộng Sản Việt Nam ",
            uri: "api/party ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 24,
        service_management_id: 1,
        name: "Nhóm phòng ban ",
        slug: "department-group ",
        status: 1,
        service_name: "Nhân sự ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 82,
            table_management_id: 24,
            name: "Tạo nhóm phòng ban ",
            uri: "api/department-group ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 83,
            table_management_id: 24,
            name: "Sửa nhóm phòng ban ",
            uri: "api/department-group/{department_group} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 84,
            table_management_id: 24,
            name: "Xoá nhóm phòng ban ",
            uri: "api/department-group/{department_group} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 85,
            table_management_id: 24,
            name: "Xem chi tiết nhóm phòng ban ",
            uri: "api/department-group/{department_group} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 86,
            table_management_id: 24,
            name: "Xem danh sách nhóm phòng ban ",
            uri: "api/department-group ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Vai trò & Quyền ",
    slug: "user-service ",
    description: null,
    domain: "https://employee.tuoitre.vn ",
    status: 1,
    created_at: "2022-02-21T07:17:22.000000Z ",
    updated_at: "2022-02-21T07:17:22.000000Z ",
    groups: [
      {
        id: 25,
        service_management_id: 2,
        name: "Quyền ",
        slug: "permission ",
        status: 1,
        service_name: "Vai trò & Quyền ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 87,
            table_management_id: 25,
            name: "Tạo quyền ",
            uri: "api/permission ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 88,
            table_management_id: 25,
            name: "Sửa quyền ",
            uri: "api/permission/{permission} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 89,
            table_management_id: 25,
            name: "Xoá quyền ",
            uri: "api/permission/{permission} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 90,
            table_management_id: 25,
            name: "Xem chi tiết quyền ",
            uri: "api/permission/{permission} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 91,
            table_management_id: 25,
            name: "Xem danh sách quyền ",
            uri: "api/permission ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 26,
        service_management_id: 2,
        name: "Quyền CD-PB ",
        slug: "permission-department-position ",
        status: 1,
        service_name: "Vai trò & Quyền ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 92,
            table_management_id: 26,
            name: "Xem danh sách phòng ban - chức danh đã được gán quyền ",
            uri: "api/permission/departments/positions/list ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 93,
            table_management_id: 26,
            name: "Xem danh sách quyền chưa được gán cho phòng ban + chức danh cụ thể ",
            uri: "api/permission/departments/positions/except ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 94,
            table_management_id: 26,
            name: "Xem danh sách quyền theo phòng ban + chức danh cụ thể ",
            uri: "api/permission/departments/positions ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 27,
        service_management_id: 2,
        name: "Quyền CD ",
        slug: "permission-position ",
        status: 1,
        service_name: "Vai trò & Quyền ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 95,
            table_management_id: 27,
            name: "Xem danh sách chức danh đã được gán quyền ",
            uri: "api/permission/work-formality/list ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 96,
            table_management_id: 27,
            name: "Xem danh sách quyền chưa được gán cho chức danh cụ thể ",
            uri: "api/permission/positions/except ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 97,
            table_management_id: 27,
            name: "Xem danh sách quyền theo chức danh cụ thể ",
            uri: "api/list/permission/work-formality/{pos_id} ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Quy trình làm việc ",
    slug: "workflow-service ",
    description: null,
    domain: null,
    status: 1,
    created_at: "2022-02-21T07:17:22.000000Z ",
    updated_at: "2022-02-21T07:17:22.000000Z ",
    groups: [
      {
        id: 17,
        service_management_id: 4,
        name: "Quy trình làm việc ",
        slug: "workflow ",
        status: 1,
        service_name: "Quy trình làm việc ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 60,
            table_management_id: 17,
            name: "Tạo loại tài liệu ",
            uri: "api/document-type/store ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 61,
            table_management_id: 17,
            name: "Cập nhật loại tài liệu ",
            uri: "api/document-type/update/{id} ",
            method: "post ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 62,
            table_management_id: 17,
            name: "Xóa loại tài liệu ",
            uri: "api/document-type/delete/{id} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 63,
            table_management_id: 17,
            name: "Xem danh sách loại tài liệu ",
            uri: "api/document-type/get-document-types ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Tài liệu ",
    slug: "document-service ",
    description: null,
    domain: null,
    status: 1,
    created_at: "2022-02-21T07:17:22.000000Z ",
    updated_at: "2022-02-21T07:17:22.000000Z ",
    groups: [
      {
        id: 13,
        service_management_id: 5,
        name: "Chung ",
        slug: "common ",
        status: 1,
        service_name: "Tài liệu ",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 41,
            table_management_id: 13,
            name: "Tạo đi nước ngoài ",
            uri: "api/go-abroad ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 42,
            table_management_id: 13,
            name: "Sửa đi nước ngoài ",
            uri: "api/go-abroad/{go_abroad} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 43,
            table_management_id: 13,
            name: "Xoá đi nước ngoài ",
            uri: "api/go-abroad/{go_abroad} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 44,
            table_management_id: 13,
            name: "Xem chi tiết đi nước ngoài ",
            uri: "api/go-abroad/users/{user_id} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 45,
            table_management_id: 13,
            name: "Xem danh sách đi nước ngoài ",
            uri: "api/go-abroad ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 18,
        service_management_id: 5,
        name: "Loại tài liệu ",
        slug: "document-type ",
        status: 1,
        service_name: "Tài liệu ",
        is_display: 1,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 64,
            table_management_id: 18,
            name: "Tạo bản mẫu tài liệu ",
            uri: "api/document-template/store ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 65,
            table_management_id: 18,
            name: "Cập nhật bản mẫu tài liệu ",
            uri: "api/document-template/update/{id} ",
            method: "post ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 66,
            table_management_id: 18,
            name: "Xem bản mẫu tài liệu ",
            uri: "api/document-template/get ",
            method: "get ",
            action: "view ",
            param: null,
            body: "{type_id:{required:true}}",
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
      {
        id: 20,
        service_management_id: 5,
        name: "Tài liệu ",
        slug: "document ",
        status: 1,
        service_name: "Tài liệu ",
        is_display: 0,
        created_at: "2022-02-21T07:17:22.000000Z ",
        updated_at: "2022-02-21T07:17:22.000000Z ",
        permissions: [
          {
            id: 67,
            table_management_id: 20,
            name: "Tạo Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ ",
            uri: "api/training-fostering ",
            method: "post ",
            action: "create ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 68,
            table_management_id: 20,
            name: "Sửa Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ ",
            uri: "api/training-fostering/{training_fostering} ",
            method: "put ",
            action: "update ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 69,
            table_management_id: 20,
            name: "Xoá Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ ",
            uri: "api/training-fostering/{training_fostering} ",
            method: "delete ",
            action: "delete ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 70,
            table_management_id: 20,
            name: "Xem chi tiết Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ ",
            uri: "api/training-fostering/users/{user_id} ",
            method: "get ",
            action: "view ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
          {
            id: 71,
            table_management_id: 20,
            name: "Xem danh sách Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị ngoại ngữ ",
            uri: "api/training-fostering ",
            method: "get ",
            action: "list ",
            param: null,
            body: null,
            option: null,
            is_display: 1,
            status: 1,
            created_at: "2022-03-10 09:26:02 ",
            updated_at: "2022-03-10 09:26:02",
          },
        ],
      },
    ],
  },
];
